name: The podbard
author: Songmu
description: Install podbard and build
inputs:
  setup:
    description: "Just setup podbard without build"
  directory:
    description: "A directory to build"
    default: "."
  destination:
    description: "A destinaion to build your site"
  parents:
    description: "Whether to dig the site's path structure as a parent directory under destination."
  version:
    description: "A version to install podbard"
    default: "v0.0.5"
runs:
  using: "composite"
  steps:
  - run: |
      TEMP_PATH="$(mktemp -d)"
      curl -sfL https://raw.githubusercontent.com/Songmu/podbard/main/install.sh | sh -s -- -b "${TEMP_PATH}" "${{ inputs.version }}" 2>&1
      sudo mv ${TEMP_PATH}/podbard /usr/local/bin/podbard
      rm -rf ${TEMP_PATH}

      if [ "${{ inputs.setup }}" = "true" ]; then
        exit 0
      fi

      parents=""
      if [ "${{ inputs.parents }}" = "true" ]; then
        parents="--parents"
      fi

      destination=""
      if [ -n "${{ inputs.destination }}" ]; then
        destination="--destination ${inputs.destination}"
      fi

      podbard -C "${{ inputs.directory }}" build ${destination} ${parents}

    shell: bash
