name: release
description: release podbard
inputs:
  tag:
    description: tag name to be released
    default: ''
  token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
  - name: setup go
    uses: actions/setup-go@v5
    with:
      go-version: stable
  - name: release
    run: |
      make crossbuild upload
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
  - uses: haya14busa/action-update-semver@v1
    with:
      major_version_tag_only: true
